############################################################################
# Extraction of .mzxml data using XCMS in R-Metabolomics data Prof Prakash #
############################################################################
# Author(s): Shiv
# Version: 24032015

# Input: ".txt" file from XCMS Metabolomics data (data matrix generated by Peter Benke)
# Software: XCMS
## SCRIPT for Rice metabolomics data from Ram (NUS-DBS)
#MS analysis performed by Peter Benke and Amit Rai -There are 2 datasets
#MS date: 2014 
#Data location 1 (statistician) (both raw and processed) : F:\Projects\NUS\RiceProject\Metabolomics\data
#Data location 2 (biologist) : Peter Benke
#Sample extraction was performed by Ram/Peter (NERI), MS analysis by Peter Benke (NERI)
# The file "RiceMetabolomicsData.txt" contains the metabolomics profiles generated in positive mode by Peter Benke.
## Data analysis for positive mode

#To identify a set of metabolites characteristic of gain of function and loss of function mutant in Rice
#There are 4 biological replicates and two technical replicate for each biological replicate- 
#Total number of sample = 6*4*2= 48 + 9 Blanks --> 57 columns

#The profiles are generated for  #(first X denotes biorep and second X techrep number)
#Lines                  GivenName       ModifiedName(SampleGroup)
#WT                     - WTXTX         WT
#Mutant                 - MXTX          MU
#Ectopic expression     - EXTX          EC
#RNAi neutral           - RNXTX         RN
#RNAi lines             - RXTX          RL
#Complementation strain - COXTX         CO
#Blank                  - BlankX        BL

#############
# Clear all #
#############
rm(list = ls()) # Clears the workspace
graphics.off() # Close all windows

##### Loading required packages 
library(xcms)
library(CAMERA)

#############
# User      #
# Specific  #
# Variables #
#############

setwd('J:/F_projects/Projects/NUS/RiceProject/Metabolomics/rawData/2 week PB')

## Parameters for AB SCIEX

set1<-xcmsSet(nSlaves=12,method='centWave',ppm=15,peakwidth=c(10,60), prefilter=c(0,0),snthresh=6,mzdiff=0.01,)
save(set1,file="set1_PB_240315_xcms1_4.rda")
set2 <- group(set1,bw=5,mzwid=0.015,minfrac=0.66) 
set3 <- retcor(set2,method="obiwarp",plottype="none")
set4 <- group(set3,bw=5,mzwid=0.015,minfrac=0.66)
save(set4,file="set4_PB_240315_xcms1_4.rda")

set5 <- fillPeaks(set4) 
save(set5,file="set5_PB_240315_xcms1_4.rda")

peaklist<-peakTable(set5,filebase="PB_240315_xcms1_38")


xsa<-xsAnnotate(set5)
xsaF<-groupFWHM(xsa, perfwhm=0.6)
xsaC<-groupCorr(xsaF)
xsaFI<-findIsotopes(xsaC)
xsaFA<-findAdducts(xsaFI, polarity='positive')
peaklist<-getPeaklist(xsaFA)
write.csv(peaklist, file='PB_240315_xcms1_4_camera.csv')
